from . import wizard_bonos
from . import wizard_cambio_plan
from . import wizard_cambio_habitacion
from . import wizard_factura_consumos
from . import wizard_consumo
from . import wizard_desasigna
from . import wizard_descuento
from . import wizard_asignacion

from . import wizard_confirm_prestados
from . import wizard_docto
from . import wizardabonos
from . import wizardhabitacion
from . import wizardplaca
from . import wizardprecuenta
from . import wizardrecaudos
from . import wizard_editarecaudo
from . import wizard_entregaolvidados
from . import wizard_entregaprestados
from . import wizard_factura_anomalia
from . import wizard_fuera_servicio
from . import wizard_fuera_uso
from . import wizard_observacion
from . import wizard_prenda
from . import wizard_reservas
from . import wizard_utilidades
from . import wizard_cierre_turno